#pragma once
#define MYENGINE_PRAGMA(x) __pragma(x)

#define MYENGINE_SUPPRESS_WARNING_PUSH MYENGINE_PRAGMA(warning (push))

#define MYENGINE_SUPPRESS_WARNING_POP MYENGINE_PRAGMA(warning(pop))

#define MYENGINE_WARNING(w) MYENGINE_PRAGMA(warning(disable: w))

#define MYENGINE_SUPPRESS_WARNING	\
MYENGINE_WARNING(4061)				\
MYENGINE_WARNING(4062)				\
MYENGINE_WARNING(4127)				\
MYENGINE_WARNING(4263)				\
MYENGINE_WARNING(4264)				\
MYENGINE_WARNING(4266)				\
MYENGINE_WARNING(4265)				\
MYENGINE_WARNING(4365)				\
MYENGINE_WARNING(4514)				\
MYENGINE_WARNING(4619)				\
MYENGINE_WARNING(4623)				\
MYENGINE_WARNING(4625)				\
MYENGINE_WARNING(4626)				\
MYENGINE_WARNING(4668)				\
MYENGINE_WARNING(4702)				\
MYENGINE_WARNING(4710)				\
MYENGINE_WARNING(4711)				\
MYENGINE_WARNING(4777)				\
MYENGINE_WARNING(4820)				\
MYENGINE_WARNING(5026)				\
MYENGINE_WARNING(5027)				\
MYENGINE_WARNING(5039)				\
MYENGINE_WARNING(5204)				\
MYENGINE_WARNING(5219)				\
MYENGINE_WARNING(5220)				\
MYENGINE_WARNING(5246)				\
MYENGINE_WARNING(5266)				\
MYENGINE_WARNING(5267)

#define MYENGINE_SUPPRESS_WARNINGS_BEGIN \
MYENGINE_SUPPRESS_WARNING_PUSH \
MYENGINE_SUPPRESS_WARNING

#define MYENGINE_SUPPRESS_WARNINGS_END \
MYENGINE_SUPPRESS_WARNING_POP